# SERVER va APP CONFIG
spring.application.name=intern_matching
server.port=8080
apiPrefix=/api/v1


# DATABASE CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/intern_matching
spring.datasource.username=root
spring.datasource.password=10032006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA va HIBERNATE
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#  DATABASE SEEDING (TỰ ĐỘNG BƠM DỮ LIỆU)
# Đợi Hibernate tạo bảng xong mới chạy file data.sql
spring.jpa.defer-datasource-initialization=true
# Bắt buộc luôn chạy file data.sql lúc khởi động
spring.sql.init.mode= never



# FILE UPLOAD
tailinh.upload-file.base-uri=D:/uploads/

# SECURITY CONFIG (Basic)
spring.security.user.name=tailinh
spring.security.user.password=10032006

# JWT CONFIG
tailinh.jwt.base64-secret=bXlzZWNyZXRrZXlibXlzZWNyZXRrZXlibXlzZWNyZXRrZXlibXlzZWNyZXRrZXl
tailinh.jwt.access-token-validity-in-seconds=6000
tailinh.jwt.refresh-token-validity-in-seconds=8640000

#  PAGINATION va FORMATTING
# Phân trang bắt đầu từ 1 thay vì 0
spring.data.web.pageable.one-indexed-parameters=true
# Ép định dạng LocalDate thành yyyy-MM-dd
spring.mvc.converters.preferred-json-mapper=jackson
spring.jackson.serialization.write-dates-as-timestamps=false


# hiển thị log có màu
spring.output.ansi.enabled=ALWAYS

# Skip lỗi khi Jackson serialize tạo bean (proxy) rỗng
spring.jackson.serialization.fail-on-empty-beans=false


